#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : python-mimeparse
Version  : 0.1.4
Release  : 11
URL      : https://pypi.python.org/packages/source/p/python-mimeparse/python-mimeparse-0.1.4.tar.gz
Source0  : https://pypi.python.org/packages/source/p/python-mimeparse/python-mimeparse-0.1.4.tar.gz
Summary  : A module provides basic functions for parsing mime-type names and matching them against a list of media-ranges.
Group    : Development/Tools
License  : MIT
Requires: python-mimeparse-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
This module provides basic functions for parsing mime-type names and matching them against a list of media-ranges.

%package python
Summary: python components for the python-mimeparse package.
Group: Default

%description python
python components for the python-mimeparse package.


%prep
%setup -q -n python-mimeparse-0.1.4

%build
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=intel.com,localhost
python mimeparse_test.py
%install
rm -rf %{buildroot}
python2 setup.py build -b py2 install --root=%{buildroot}
python3 setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
